services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=boot
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ management console

  authorization-service:
    container_name: authorization-service
    build: ./authorizationservice
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=spring
      - spring.datasource.password=boot
      - spring.datasource.driver-class-name=org.postgresql.Driver
    depends_on:
      - db
    ports:
      - 8081:8081

  order-service:
    container_name: order-service
    build: ./orderservice
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=spring
      - spring.datasource.password=boot
      - spring.datasource.driver-class-name=org.postgresql.Driver
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8082:8082

  notification-service:
    container_name: notification-service
    build: ./notificationservice
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=spring
      - spring.datasource.password=boot
      - spring.datasource.driver-class-name=org.postgresql.Driver
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8083:8083

  packaging-and-delivery-service:
    container_name: packaging-and-delivery-service
    build: ./packaginganddeliveryservice
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=spring
      - spring.datasource.password=boot
      - spring.datasource.driver-class-name=org.postgresql.Driver
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8084:8084

  products-service:
    container_name: products-service
    build: ./productsservice
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=spring
      - spring.datasource.password=boot
      - spring.datasource.driver-class-name=org.postgresql.Driver
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8085:8085