services:
  order-service:
    container_name: order-service
    build: .
    environment:
      - spring.datasource.url=jdbc:postgresql://db:5432/postgres
      - spring.datasource.username=spring
      - spring.datasource.password=boot
      - spring.datasource.driver-class-name=org.postgresql.Driver
    depends_on:
      - db
      - rabbitmq
    ports:
      - 8082:8082

  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=spring
      - POSTGRES_PASSWORD=boot
      - POSTGRES_DB=postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./database-data:/var/lib/postgresql/data/

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ management console